import type { IRComponent, IRParam } from "../ir/types.js"
import { emitRoot, ind, type Ctx } from "./emit-node.js"
import { GenError, kebab, type GenTokens } from "./maps.js"

export const fileName = (c: Pick<IRComponent, "name">): string => `${kebab(c.name)}.tsx`

const tsType = (p: IRParam): string => {
  switch (p.type) {
    case "string":
    case "icon":
      return "string"
    case "number":
    case "boolean":
      return p.type
    case "enum":
      return (p.values ?? []).map((v) => JSON.stringify(v)).join(" | ")
    case "action":
      return "() => void"
    case "array":
      return `{ ${(p.fields ?? []).map((f) => `${f.name}: ${f.type}`).join("; ")} }[]`
    case "child":
      throw new GenError(`child param "${p.name}" is not supported`)
  }
}

const ICON_HELPER = [
  'function LoomIcon({ name, className }: { name?: string; className?: string }) {',
  '  const Cmp = name ? icons[name.split("-").map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join("") as keyof typeof icons] : undefined',
  '  return Cmp ? <Cmp className={className} aria-hidden="true" /> : null',
  "}",
]

export function emitComponent(ir: IRComponent, tokens: GenTokens, cnImport: string): string {
  const ctx: Ctx = {
    name: ir.name.charAt(0).toLowerCase() + ir.name.slice(1),
    params: ir.params,
    tokens,
    cvas: [],
    usesCn: false,
    usesIcon: false,
    components: new Map(),
  }
  const jsx = emitRoot(ir.root, ctx)

  const imports = [
    ...(ctx.cvas.length ? ['import { cva } from "class-variance-authority"'] : []),
    ...(ctx.usesIcon ? ['import { icons } from "lucide-react"'] : []),
    ...(ctx.usesCn ? [`import { cn } from ${JSON.stringify(cnImport)}`] : []),
    ...[...ctx.components].sort(([a], [b]) => (a < b ? -1 : 1)).map(([n, path]) => `import { ${n} } from ${JSON.stringify(path)}`),
  ]

  const props = ir.params.map((p) => `${p.name}${p.required ? "" : "?"}: ${tsType(p)}`)
  const destructured = [
    ...ir.params.map((p) => (p.default === undefined ? p.name : `${p.name} = ${JSON.stringify(p.default)}`)),
    ...(ctx.usesCn ? ["className"] : []),
  ]
  const propsType = ctx.usesCn ? `${ir.name}Props & { className?: string }` : `${ir.name}Props`
  const body = jsx.length === 1 ? [`return ${jsx[0]}`] : ["return (", ...ind(jsx), ")"]

  const sections: string[][] = [
    [`// @generated by loom — do not edit. source: ${ir.source} hash: ${ir.hash} id: ${ir.id}`, ...imports],
    ...(ctx.cvas.length ? [ctx.cvas] : []),
    ...(ctx.usesIcon ? [ICON_HELPER] : []),
    [`export interface ${ir.name}Props { ${props.join("; ")} }`],
    [
      `export function ${ir.name}({ ${destructured.join(", ")} }: ${propsType}) {`,
      ...ind(body),
      "}",
    ],
  ]
  return sections.map((s) => s.join("\n")).join("\n\n") + "\n"
}

