import { execFileSync } from "node:child_process"
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs"
import { createRequire } from "node:module"
import { tmpdir } from "node:os"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath, pathToFileURL } from "node:url"
import { describe, expect, test } from "vitest"
import type { IRComponent, IRExpr, IRNode } from "../ir/types.js"
import { emitComponent } from "./emit-component.js"
import { generateWeb, runGenWeb } from "./gen.js"
import type { GenTokens } from "./maps.js"

const demo = resolve(dirname(fileURLToPath(import.meta.url)), "../../../../examples/demo-ds")
const distDir = join(demo, "dist/web/src/components/loom")
const tokens: GenTokens = {
  spacing: { 1: 4, 2: 8, 3: 12, 4: 16, 6: 24, 8: 32 },
  radius: new Set(["sm", "md", "lg", "full"]),
}
const ir = (name: string): IRComponent => JSON.parse(readFileSync(join(demo, ".loom", `${name}.ir.json`), "utf8"))
const gen = (name: string): string => emitComponent(ir(name), tokens, "@/lib/utils")

const normalize = (src: string): string =>
  src.replace(/"([^"\n]*)"/g, (_, s: string) => `"${s.split(/\s+/).filter(Boolean).sort().join(" ")}"`)

const BADGE_EXAMPLE = `// @generated by loom — do not edit. source: components/Badge/Badge.loom.tsx hash: <hash> id: cmp_badge
import { cva } from "class-variance-authority"
import { cn } from "@/lib/utils"

const badgeVariants = cva("grid h-5 place-items-center relative rounded-full w-5 *:col-start-1 *:row-start-1", {
  variants: { tone: { accent: "bg-primary", danger: "bg-destructive" } },
  defaultVariants: { tone: "danger" },
})
const badgeN0_0Variants = cva("text-[11px] leading-[13px]", {
  variants: { tone: { accent: "text-primary-foreground", danger: "text-destructive-foreground" } },
  defaultVariants: { tone: "danger" },
})

export interface BadgeProps { count: number; tone?: "accent" | "danger" }

export function Badge({ count, tone = "danger", className }: BadgeProps & { className?: string }) {
  return (
    <div className={cn(badgeVariants({ tone }), className)}>
      <span className={badgeN0_0Variants({ tone })}>{count > 99 ? "99+" : String(count)}</span>
    </div>
  )
}
`

const classSets = (src: string): string[][] =>
  [...src.matchAll(/"([^"\n]*)"/g)].map((m) => (m[1] as string).split(/\s+/).sort())

describe("demo-ds output", () => {
  test("Badge matches the normative example (class sets + structure)", () => {
    const out = gen("Badge")
    expect(normalize(out)).toBe(normalize(BADGE_EXAMPLE.replace("<hash>", ir("Badge").hash)))
    expect(classSets(out)).toContainEqual(["*:col-start-1", "*:row-start-1", "grid", "h-5", "place-items-center", "relative", "rounded-full", "w-5"])
  })

  test("Button variants", () => {
    const out = gen("Button")
    expect(out).toMatch(/const buttonVariants = cva\(/)
    expect(out).toMatch(/intent: \{ destructive: "bg-destructive", ghost: "bg-transparent", primary: "bg-primary", secondary: "bg-secondary" \}/)
    expect(out).toMatch(/size: \{ lg: "p-4", md: "p-3", sm: "p-2" \}/)
    const icon = out.slice(out.indexOf("const buttonN0_0Variants"), out.indexOf("const buttonN0_1Variants"))
    expect(icon).toMatch(/intent: \{/)
    expect(icon).toMatch(/size: \{ lg: "size-5", md: "size-\[18px\]", sm: "size-\[14px\]" \}/)
    expect(out).toContain("hover:opacity-90")
    expect(out).toContain("disabled:opacity-50")
    expect(out).toContain('<button type="button"')
  })

  test("Catalog layout, keys and sibling imports", () => {
    const out = gen("Catalog")
    expect(out).toContain('import { Badge } from "./badge"')
    expect(out).toContain('import { Button } from "./button"')
    expect(out).toContain('<div className="flex flex-row items-center justify-between self-stretch">')
    expect(out).toContain('role="separator"')
    expect(out).toContain("items.map((item) => (")
    expect(out).toContain("key={item.id}")
    expect(out).toContain('<Button intent="secondary" label="Load more" onPress={onLoadMore} size="sm" />')
  })

  test("committed output is byte-identical to a fresh generation (golden)", () => {
    const irs = readdirSync(join(demo, ".loom")).filter((f) => f.endsWith(".ir.json")).map((f) => ir(f.replace(".ir.json", "")))
    const { files, diagnostics } = generateWeb(irs, tokens, "@/lib/utils")
    expect(diagnostics).toEqual([])
    expect([...files.keys()]).toEqual(["badge.tsx", "button.tsx", "catalog.tsx"])
    for (const [f, text] of files) expect(readFileSync(join(distDir, f), "utf8")).toBe(text)
    for (const text of files.values()) expect(text.endsWith("\n") && !text.endsWith("\n\n")).toBe(true)
  })
})

const stack = (type: "HStack" | "VStack", props: Record<string, IRExpr> = {}, children: IRNode[] = [], id = "n0"): IRNode => ({
  kind: "primitive", id, type, props, children,
})
const comp = (root: IRNode, extra: Partial<IRComponent> = {}): IRComponent => ({
  irVersion: 1, id: "cmp_x", name: "X", version: "1.0.0", source: "X.loom.tsx", hash: "0".repeat(12), params: [], root, ...extra,
})
const emit = (c: IRComponent): string => emitComponent(c, tokens, "@/lib/utils")
const fill: Record<string, IRExpr> = { width: { lit: "fill" }, height: { lit: "fill" } }
const classAttrs = (out: string): string[][] =>
  [...out.matchAll(/className="([^"]*)"/g)].map((m) => (m[1] as string).split(" "))

describe("synthetic cases", () => {
  test("fill resolves against the parent axis", () => {
    const inRow = classAttrs(emit(comp(stack("HStack", {}, [stack("VStack", fill, [], "n0.0")]))))[0]
    expect(inRow).toEqual(["flex", "flex-1", "flex-col", "min-w-0", "self-stretch"])
    const inCol = classAttrs(emit(comp(stack("VStack", {}, [stack("HStack", fill, [], "n0.0")]))))[0]
    expect(inCol).toEqual(["flex", "flex-1", "flex-row", "min-h-0", "self-stretch"])
  })

  test("child params are LOOM301", () => {
    const c = comp(stack("VStack"), { params: [{ name: "slot", type: "child", required: true }] })
    const { diagnostics } = generateWeb([c], tokens, "@/lib/utils")
    expect(diagnostics).toMatchObject([{ code: "LOOM301", file: "X.loom.tsx" }])
  })

  test("missing class mappings are LOOM301, never silently emitted", () => {
    const bad = (props: Record<string, IRExpr>) =>
      generateWeb([comp(stack("HStack", props))], tokens, "@/lib/utils").diagnostics.map((d) => d.code)
    expect(bad({ gap: { lit: 5 } })).toEqual(["LOOM301"])
    expect(bad({ cornerRadius: { lit: "huge" } })).toEqual(["LOOM301"])
    expect(bad({ nonsense: { lit: 1 } })).toEqual(["LOOM301"])
  })

  test("boolean params produce true/false variant keys", () => {
    const out = emit(
      comp(stack("HStack", { clip: { param: "on" } }), { params: [{ name: "on", type: "boolean", required: false }] }),
    )
    expect(out).toContain('variants: { on: { false: "", true: "overflow-hidden" } }')
    expect(out).toContain("defaultVariants: { on: false }")
  })
})

describe("drift check", () => {
  const project = (): string => {
    const dir = mkdtempSync(join(tmpdir(), "loom-gen-"))
    writeFileSync(join(dir, "loom.config.ts"), `export default ${JSON.stringify({
      tokens: "./loom.tokens.ts", components: "./c/**/*.loom.tsx",
      out: { generated: "./generated", ir: "./.loom", web: "./dist/web" },
      web: { cnImport: "@/lib/utils", componentDir: "src/components/loom" },
    })}\n`)
    writeFileSync(join(dir, "loom.tokens.ts"), `export default ${JSON.stringify({
      spacing: tokens.spacing, radius: { sm: 6, md: 8, lg: 16, full: 999 },
    })}\n`)
    cpSync(join(demo, ".loom"), join(dir, ".loom"), { recursive: true })
    return dir
  }

  test("clean tree passes, mutation and orphans fail with LOOM320", async () => {
    const dir = project()
    try {
      expect(await runGenWeb(dir)).toEqual([])
      expect(await runGenWeb(dir, { check: true })).toEqual([])
      const out = join(dir, "dist/web/src/components/loom")
      for (const f of readdirSync(out)) expect(readFileSync(join(out, f), "utf8")).toBe(readFileSync(join(distDir, f), "utf8"))

      const badge = join(out, "badge.tsx")
      const original = readFileSync(badge, "utf8")
      writeFileSync(badge, original + "// edit\n")
      const drift = await runGenWeb(dir, { check: true })
      expect(drift).toMatchObject([{ code: "LOOM320", file: "dist/web/src/components/loom/badge.tsx" }])
      writeFileSync(badge, original)

      rmSync(join(dir, ".loom/Badge.ir.json"))
      const orphan = await runGenWeb(dir, { check: true })
      expect(orphan.map((d) => d.code)).toEqual(["LOOM320"])
      expect(existsSync(badge)).toBe(true)
      expect(await runGenWeb(dir)).toEqual([])
      expect(existsSync(badge)).toBe(false)
    } finally {
      rmSync(dir, { recursive: true, force: true })
    }
  })
})

describe("generated code", () => {
  test("typechecks in a standalone project", () => {
    const dir = mkdtempSync(join(demo, ".tmp-gen-"))
    try {
      const irs = readdirSync(join(demo, ".loom")).map((f) => ir(f.replace(".ir.json", "")))
      const { files } = generateWeb(irs, tokens, "@/lib/utils")
      mkdirSync(join(dir, "lib"))
      writeFileSync(join(dir, "lib/utils.ts"), "export const cn = (...xs: Array<string | undefined>): string => xs.filter(Boolean).join(' ')\n")
      for (const [f, text] of files) writeFileSync(join(dir, f), text)
      writeFileSync(join(dir, "tsconfig.json"), JSON.stringify({
        compilerOptions: {
          strict: true, noUncheckedIndexedAccess: true, target: "ES2022", module: "ESNext", moduleResolution: "Bundler",
          jsx: "react-jsx", noEmit: true, skipLibCheck: true, types: [], baseUrl: ".", paths: { "@/lib/utils": ["./lib/utils.ts"] },
        },
        include: ["*.tsx", "lib/*.ts"],
      }))
      const tsc = createRequire(join(demo, "package.json")).resolve("typescript/bin/tsc")
      execFileSync(process.execPath, [tsc, "-p", dir], { stdio: "pipe" })
    } catch (e) {
      const err = e as { stdout?: Buffer }
      throw new Error(err.stdout?.toString() || String(e))
    } finally {
      rmSync(dir, { recursive: true, force: true })
    }
  })

  test("Button renders with shadcn classes", async () => {
    const req = createRequire(join(demo, "package.json"))
    const React = req("react") as { createElement: (c: unknown, p: unknown) => unknown }
    const { renderToStaticMarkup } = req("react-dom/server") as { renderToStaticMarkup: (e: unknown) => string }
    const mod = (await import(/* @vite-ignore */ pathToFileURL(join(distDir, "button.tsx")).href)) as { Button: unknown }
    const html = renderToStaticMarkup(React.createElement(mod.Button, { label: "Go" }))
    expect(html).toContain("bg-primary")
    expect(html).toContain("rounded-full")
    expect(html).toContain(">Go<")
  })
})
