import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs"
import { relative, resolve } from "node:path"
import type { Diagnostic } from "../diagnostics.js"
import { loadConfig, loadTsModule } from "../config.js"
import type { IRComponent } from "../ir/types.js"
import type { TokensDef } from "../tokens/define.js"
import { emitComponent, fileName } from "./emit-component.js"
import { GenError, type GenTokens } from "./maps.js"

export const GENERATED_MARK = "// @generated by loom"

export const tokensFromDef = (def: TokensDef): GenTokens => ({
  spacing: def.spacing,
  radius: new Set(Object.keys(def.radius)),
})

export interface GenResult {
  /** file name → contents */
  files: Map<string, string>
  diagnostics: Diagnostic[]
}

export function generateWeb(irs: IRComponent[], tokens: GenTokens, cnImport: string): GenResult {
  const files = new Map<string, string>()
  const diagnostics: Diagnostic[] = []
  for (const ir of [...irs].sort((a, b) => (a.name < b.name ? -1 : 1))) {
    try {
      files.set(fileName(ir), emitComponent(ir, tokens, cnImport))
    } catch (e) {
      const code = (e as { code?: unknown }).code
      if (!(e instanceof GenError) && typeof code !== "string") throw e
      diagnostics.push({
        code: typeof code === "string" ? code : "LOOM301",
        severity: "error",
        file: ir.source,
        line: 1,
        col: 1,
        message: `${ir.name}: ${(e as Error).message.replace(/^LOOM\d+ /, "")}`,
      })
    }
  }
  return { files, diagnostics }
}

const generatedOnDisk = (dir: string): string[] =>
  existsSync(dir)
    ? readdirSync(dir)
        .filter((f) => f.endsWith(".tsx") && readFileSync(resolve(dir, f), "utf8").startsWith(GENERATED_MARK))
        .sort()
    : []

export async function runGenWeb(cwd: string, opts: { check?: boolean } = {}): Promise<Diagnostic[]> {
  const config = await loadConfig(cwd)
  const tokens = tokensFromDef(await loadTsModule<TokensDef>(resolve(cwd, config.tokens)))
  const irDir = resolve(cwd, config.out.ir)
  const irs = existsSync(irDir)
    ? readdirSync(irDir)
        .filter((f) => f.endsWith(".ir.json"))
        .sort()
        .map((f) => JSON.parse(readFileSync(resolve(irDir, f), "utf8")) as IRComponent)
    : []
  const { files, diagnostics } = generateWeb(irs, tokens, config.web.cnImport)
  if (diagnostics.length > 0) return diagnostics

  const outDir = resolve(cwd, config.out.web, config.web.componentDir)
  const rel = (f: string): string => relative(cwd, resolve(outDir, f))
  const drift = (f: string, message: string): Diagnostic => ({
    code: "LOOM320", severity: "error", file: rel(f), line: 1, col: 1, message,
  })
  const orphans = generatedOnDisk(outDir).filter((f) => !files.has(f))

  if (opts.check) {
    const out: Diagnostic[] = []
    for (const [f, text] of files) {
      const path = resolve(outDir, f)
      if (!existsSync(path) || readFileSync(path, "utf8") !== text) {
        out.push(drift(f, "generated file is out of date; run loom gen web"))
      }
    }
    for (const f of orphans) out.push(drift(f, "generated file has no IR source; run loom gen web"))
    return out
  }

  mkdirSync(outDir, { recursive: true })
  for (const [f, text] of files) writeFileSync(resolve(outDir, f), text)
  for (const f of orphans) rmSync(resolve(outDir, f))
  return []
}

