import type { TokensDef } from "./define.js"
import type { Palette } from "./palette.js"
import { kebab } from "./kebab.js"

export const header = (hash: string): string =>
  `@generated by loom — do not edit. source: loom.tokens.ts hash: ${hash}`

// [shadcn var, loom role]; --radius is handled separately.
export const SHADCN_ALIASES: Array<[string, string]> = [
  ["background", "surface"],
  ["foreground", "textPrimary"],
  ["card", "surfaceRaised"],
  ["card-foreground", "textPrimary"],
  ["popover", "surfaceRaised"],
  ["popover-foreground", "textPrimary"],
  ["primary", "accent"],
  ["primary-foreground", "onAccent"],
  ["secondary", "surfaceRaised"],
  ["secondary-foreground", "textPrimary"],
  ["muted", "surfaceRaised"],
  ["muted-foreground", "textMuted"],
  ["accent", "accentSoft"],
  ["accent-foreground", "textPrimary"],
  ["destructive", "danger"],
  ["destructive-foreground", "onDanger"],
  ["border", "separator"],
  ["input", "separator"],
  ["ring", "accent"],
]

export function emitCss(def: TokensDef, palette: Palette, hash: string): string {
  const roots: string[] = []
  const theme: string[] = []

  for (const [role, hex] of Object.entries(palette.colors)) {
    roots.push(`  --loom-color-${kebab(role)}: ${hex};`)
  }
  roots.push("  --loom-color-transparent: transparent;")
  for (const [seed, ramp] of Object.entries(palette.ramps)) {
    for (const [step, hex] of Object.entries(ramp)) roots.push(`  --loom-ramp-${seed}-${step}: ${hex};`)
  }
  for (const [key, px] of Object.entries(def.spacing)) roots.push(`  --loom-space-${key}: ${px}px;`)
  for (const [name, px] of Object.entries(def.radius)) roots.push(`  --loom-radius-${kebab(name)}: ${px}px;`)
  for (const [alias, role] of SHADCN_ALIASES) roots.push(`  --${alias}: var(--loom-color-${kebab(role)});`)
  roots.push("  --radius: var(--loom-radius-md);")

  for (const [alias] of SHADCN_ALIASES) theme.push(`  --color-${alias}: var(--${alias});`)
  for (const role of Object.keys(palette.colors)) {
    theme.push(`  --color-loom-${kebab(role)}: var(--loom-color-${kebab(role)});`)
  }
  theme.push("  --color-loom-transparent: var(--loom-color-transparent);")
  for (const [seed, ramp] of Object.entries(palette.ramps)) {
    for (const step of Object.keys(ramp)) {
      theme.push(`  --color-loom-${seed}-${step}: var(--loom-ramp-${seed}-${step});`)
    }
  }
  for (const name of ["sm", "md", "lg"]) {
    if (name in def.radius) theme.push(`  --radius-${name}: var(--loom-radius-${name});`)
  }

  const typography = Object.entries(def.typography).map(
    ([name, t]) =>
      `.loom-typography-${kebab(name)} { font-size: ${t.size}px; line-height: ${t.line}px; font-weight: ${t.weight}; }`,
  )

  return [
    `/* ${header(hash)} */`,
    ":root {",
    ...roots,
    "}",
    ...typography,
    "@theme inline {",
    ...theme,
    "}",
    "",
  ].join("\n")
}
